/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5TQD2YN2JVS
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function GameLobby() {
  return (
    <div className="mx-auto max-w-3xl px-4">
      <div className="space-y-6">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Join or Create Game</h1>
        </div>
        <div className="space-y-4">
          <div>
            <h2 className="text-lg font-bold">Join Game</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400">Enter the Game ID to join an existing game</p>
            <div className="grid grid-cols-12 items-center gap-4">
              <Input className="col-span-8" id="game-id" placeholder="Enter Game ID" />
              <Button className="col-span-4">Join</Button>
            </div>
            <p className="text-sm text-gray-500 dark:text-gray-400">Game ID is invalid</p>
          </div>
          <div className="border-t border-gray-200 dark:border-gray-800" />
          <div>
            <h2 className="text-lg font-bold">Create Game</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400">Click the button to create a new game</p>
            <Button>Create New Game</Button>
            <p className="text-sm text-gray-500 dark:text-gray-400">Game created. Your Game ID is: ABC123</p>
          </div>
        </div>
      </div>
    </div>
  )
}
